# list of a few triggers for github workflows

on:

  # Trigger the workflow on push
  push:
    branches: [master, develop, feature/*] # list of branches to trigger the workflow on push
    # branches-ignore: [master, develop, */feature] # list of branches to ignore
    tags: ['*', '!*-*', '!*.*.*', '!*.*.*-*', 'v*', 'v*.*', 'v*.*.*', 'v*.*.*-*',] # tags that match this pattern will trigger the workflow
    # tags-ignore: ['*', '!*-*', '!*.*.*', '!*.*.*-*', 'v*', 'v*.*', 'v*.*.*', 'v*.*.*-*',] # tags that match this pattern will not trigger the workflow
    # or as a list such as below
    # Note: you cannot use both tags and tags-ignore or branches and branches-ignore at the same time

# Trigger the workflow on cron schdeule
  schedule:
    - cron: '0 6 * * 1' # run every monday at 6am UTC
    - cron: '0 4 * * 2-5' # run every weekday at 4am UTC

# Trigger on release
  release:
    types: [created, edited, published, unpublished, released, prereleased, deleted]




# Trigger on issue
  issues:
    types: [opened, closed, reopened, edited, labeled, unlabeled]

# Trigger on pull request
  pull_request:
    types: [opened, closed, reopened, edited, labeled, unlabeled, synchronize]
    branches: [master, develop, feature/*]

# Trigger on pull request review
  pull_request_review:
    types: [submitted, edited, dismissed]

# Trigger on pull request review comment
  pull_request_review_comment:
    types: [created, edited, deleted]

# Trigger on status
  status: {}

# Trigger on check run
  check_run:
    types: [completed, requested_action, rerequested]

# Trigger on check suite
  check_suite:
    types: [completed, requested, rerequested]

# Trigger on label
  label:
    types: [created, edited, deleted]

# Trigger on milestone
  milestone:
    types: [created, closed, opened, edited, deleted]

# Trigger on project
  project:
    types: [created, closed, edited, deleted]

# Trigger on project card
  project_card:
    types: [created, moved, edited, deleted]

# Trigger on project column
  project_column:
    types: [created, moved, updated, deleted]

# Trigger on deployment
  deployment:
    types: [created, deleted, edited, ready, activated, deactivated, cancelled]

# Trigger on deployment status
  deployment_status:
    types: [created, deleted, edited, ready, activated, deactivated, cancelled]

# Trigger on page build
  page_build:
    types: [created, deleted, edited, ready, activated, deactivated, cancelled]

# Trigger on repository dispatch
  repository_dispatch:
    types: [created, deleted, edited, ready, activated, deactivated, cancelled]

# Trigger on workflow dispatch
  workflow_dispatch:
    types: [created, deleted, edited, ready, activated, deactivated, cancelled]

# Trigger on workflow run
  workflow_run:
    workflows: ["Build"]  # list of workflows to trigger on
    types: [requested, completed]  # list of types to trigger on
    branches:
      - 'releases/**'
      - '!releases/**-alpha'
      - ${{ github.action_ref }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run : echo "Hello World"
